version: '3'
services:
  rconsumer:
    build: ./
    command:
      - python3 ./RabbitMQ_Consumer.py
  msubscriber:
    build: ./
    command:
      - python3 ./MQTT_Subscriber.py
    depends_on:
    - rconsumer
  mpublisher:
    build: ./
    command:
      - python3 ./MQTT_Publisher.py
    depends_on:
    - msubscriber


